// <auto-generated />
namespace AssetManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpgradeToABP084 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpgradeToABP084));
        
        string IMigrationMetadata.Id
        {
            get { return "201604290453368_UpgradeToABP084"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
